# -*- coding: utf-8 -*-
from typing import Any

# Form implementation generated from reading ui file 'chess.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
from classe_Piece_et_filles_et_joueur import *
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QDialog, QVBoxLayout, QPushButton, QLabel
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap, QPainter, QBrush, QColor
from PyQt5.QtEffects import QGraphicsBlurEffect
from PyQt5.QtWidgets import QMessageBox
import sqlite3
from datetime import datetime
import copy

from classe_Piece_et_filles_et_joueur import Joueur


# Interface de jeu
class Ui_Jeu_d_echecs(object):
    def setupUi(self, Jeu_d_echecs):
        # Configuration de la fenêtre principale
        Jeu_d_echecs.setObjectName("Jeu_d_echecs")
        Jeu_d_echecs.resize(979, 600)

        # Widget central
        self.centralwidget = QtWidgets.QWidget(Jeu_d_echecs)
        self.centralwidget.setObjectName("centralwidget")
        Jeu_d_echecs.setCentralWidget(self.centralwidget)

        # GroupBox pour l'échiquier
        self.Echiquier = QtWidgets.QGroupBox(self.centralwidget)
        self.Echiquier.setGeometry(QtCore.QRect(30, 30, 400, 400))
        self.Echiquier.setMinimumSize(QtCore.QSize(400, 400))
        self.Echiquier.setMaximumSize(QtCore.QSize(400, 400))
        self.Echiquier.setTitle("")
        self.Echiquier.setObjectName("Echiquier")

        # QGridLayout pour l'échiquier (sans marges)
        self.gridLayout = QtWidgets.QGridLayout(self.Echiquier)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)  # Supprime les marges
        self.gridLayout.setSpacing(0)  # Supprime les espacements entre les cases
        self.gridLayout.setObjectName("gridLayout")

        # Création des 64 cases (boutons) avec leurs couleurs
        for row in range(8):
            for col in range(8):
                button_name = f"{chr(97 + col)}{8 - row}"  # Ex: A1, B1, ..., H8
                button = QtWidgets.QPushButton(self.Echiquier)
                button.setMinimumSize(QtCore.QSize(50, 50))
                button.setMaximumSize(QtCore.QSize(50, 50))
                button.setText("")
                button.setObjectName(button_name)

                # Alterner les couleurs (noir/blanc)
                if (row + col) % 2 == 0:
                    button.setStyleSheet("background-color: white;")
                else:
                    button.setStyleSheet("background-color: black;")

                # Ajouter le bouton au gridLayout
                self.gridLayout.addWidget(button, row, col)

        # Autres éléments de l'interface (listWidget, boutons, etc.)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(520, 10, 291, 311))
        self.listWidget.setObjectName("listWidget")

        # Boutons en bas à droite
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(520, 340, 295, 52))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)

        self.Abandonner = QtWidgets.QPushButton("Abandonner", self.layoutWidget)
        self.Rentrer = QtWidgets.QPushButton("Rentrer", self.layoutWidget)
        self.Rejouer = QtWidgets.QPushButton("Rejouer", self.layoutWidget)

        self.horizontalLayout_3.addWidget(self.Abandonner)
        self.horizontalLayout_3.addWidget(self.Rentrer)
        self.horizontalLayout_3.addWidget(self.Rejouer)

        # Boutons de thème et PNG
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(520, 390, 203, 52))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)

        self.theme = QtWidgets.QPushButton("Thème", self.layoutWidget1)
        self.Png = QtWidgets.QPushButton("PNG", self.layoutWidget1)

        self.horizontalLayout_2.addWidget(self.theme)
        self.horizontalLayout_2.addWidget(self.Png)

        # Barre de menu et barre de statut
        self.menubar = QtWidgets.QMenuBar(Jeu_d_echecs)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        Jeu_d_echecs.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Jeu_d_echecs)
        Jeu_d_echecs.setStatusBar(self.statusbar)

        self.retranslateUi(Jeu_d_echecs)
        QtCore.QMetaObject.connectSlotsByName(Jeu_d_echecs)



    # Pour la traduction en d'autres langues (pas obligatoire)
    def retranslateUi(self, Jeu_d_echecs):
        _translate = QtCore.QCoreApplication.translate
        Jeu_d_echecs.setWindowTitle(_translate("Jeu_d_echecs", "Jeu d\'échecs"))
        buttons_text = {
            self.Abandonner: "Abandonner",
            self.Rentrer: "Rentrer",
            self.Rejouer: "Rejouer",
            self.theme: "Thème Clair",
            self.Png: "PNG de la partie"
        }
        for button, text in buttons_text.items():
            button.setText(_translate("Jeu_d_echecs", text))

# Implémentation d'une partie de jeu

class ChessGame(QMainWindow, Ui_Jeu_d_echecs):   #Héritage multiple: la classe créée hérite de deux classes mères

    current_player: Joueur

    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Floute l'interface du jeu en arrière-plan (optionnel)
        self.blur_effect = QGraphicsBlurEffect()
        self.setGraphicsEffect(self.blur_effect)

        # Affiche la fenêtre de bienvenue
        self.welcome_dialog = WelcomeDialog(self)
        self.welcome_dialog.exec_()  # Affiche la fenêtre modale

        # Retire le flou une fois la partie lancée
        self.setGraphicsEffect(None)
         # Choix de la couleur du joueur
        reponse = QMessageBox.question(
            self,
            "Choix de la couleur",
            "Voulez-vous jouer les Blancs ?\n(Oui = Blancs, Non = Noirs)",
            QMessageBox.Yes | QMessageBox.No
        )

        self.joueur_blanc = Joueur('b')
        self.joueur_noir = Joueur('n')

        if reponse == QMessageBox.Yes:
            self.joueur_humain = self.joueur_blanc
            self.ia = self.joueur_noir
        else:
            self.joueur_humain = self.joueur_noir
            self.ia = self.joueur_blanc

        self.selected_piece = None
        # Initialise un échiquier 8x8 vide
        self.board = [[None for _ in range(8)] for _ in range(8)]  #représente l'échiquier et contient toutes les pièces vivantes
        
        self.profondeur_max = 5
        self.game_over = False
        self.current_player = self.joueur_blanc
        self.pieces_prises = []
        self.moved_pieces = []
        self.pion_avance_de_2_cases = []
        self.a_bouge = {T1n: False, Rn: False, T2n: False, T1b: False, Rb: False, T2b: False}
        self.setup_board()
        self.move_history = []
        self.show_start_message()  # Message au démarrage

        # Initialise la base de données
        self.conn = sqlite3.connect('echecs_games.db')
        self.cursor = self.conn.cursor()
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS parties(id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT, result TEXT, winner TEXT, moves TEXT )''')
        self.conn.commit()


        #connexion des boutons
        self.Abandonner.clicked.connect(self.on_abandon_clicked)
        self.Rejouer.clicked.connect(self.reset_game)
        self.Rentrer.clicked.connect(self.undo_last_move)
        # Si le joueur a choisi les noirs,
        # l'IA (blanche) joue immédiatement.
        if self.ia == self.joueur_blanc:
            QTimer.singleShot(500, self.ia_move)

    def show_start_message(self):
        msg = QMessageBox(self)
        msg.setWindowTitle("Début de partie")
        msg.setText("C'est parti !")
        msg.setStandardButtons(QMessageBox.NoButton)  # Pas de bouton
        msg.show()

        # Ferme la boîte après 2 secondes
        QTimer.singleShot(1500, msg.close)

    def setup_board(self):

        # Place les pièces noires (ligne 0)
        for col, piece in enumerate(Pieces_noires):
            self.board[0][col] = piece

        # Place les pièces blanches (ligne 7)
        for col, piece in enumerate(Pieces_blanches):
            self.board[7][col] = piece

        # Place les pions noirs (ligne 1)
        for col, piece in enumerate(Pions_noirs):
            self.board[1][col] = piece

        # Place les pions blancs (ligne 6)
        for col, piece in enumerate(Pions_blancs):
            self.board[6][col] = piece

        # Met à jour l'interface
        for piece, (row, col) in positions_initiales.items():
            button_name = f"{chr(97 + col)}{8 - row}"  # Ex: "a8" pour (0,0), "h1" pour (7,7)
            button = self.findChild(QtWidgets.QPushButton, button_name)
            if button:
                button.setText(piece)  # Utilise __repr__ de Piece
                button.setStyleSheet("font-size: 24px;")
                button.clicked.connect(partial(self.on_case_clicked, row, col))

    def on_case_clicked(self, row, col):
        if self.selected_piece is None:  # Premier clic
            piece = self.board[row][col]
            if piece and self.current_player.couleur == piece.couleur:
                self.selected_piece = (row, col)
                button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + col)}{8 - row}")
                self.reset_highlight()
                button.setStyleSheet("background-color: yellow; font-size: 24px;")

                # Gestion de la prise en passant
                m, n = None, None
                if isinstance(piece, Pion) and self.pion_avance_de_2_cases and self.moved_pieces:
                    i, j = piece.position(self.board)
                    last_piece = self.moved_pieces[-1]
                    last_pos = last_piece.position(self.board)
                    if last_pos == (i, j - 1):  # Pion à gauche
                        m, n = (i - 1, j - 1) if piece.couleur == 'b' else (i + 1, j - 1)
                    elif last_pos == (i, j + 1):  # Pion à droite
                        m, n = (i - 1, j + 1) if piece.couleur == 'b' else (i + 1, j + 1)

                # Liste des cases accessibles (incluant la prise en passant)
                L = piece.cases_accessibles(self.board)
                if (m, n) is not None:
                    L.append((m, n))

                # Surbrillance des cases accessibles
                for r, c in L:
                    case_button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + c)}{8 - r}")
                    if case_button:
                        case_button.setStyleSheet("border: 2px solid grey; font-size: 24px;")
            else:
                self.selected_piece = None
                self.reset_highlight()
        else:  # Deuxième clic
            start_row, start_col = self.selected_piece
            self.move_piece(start_row, start_col, row, col)
            self.selected_piece = None
            self.reset_highlight()

    #code du jeu
    def start_game(self):
        # Utilise un QTimer pour éviter de bloquer l'interface
        self.game_timer = QTimer(self)
        self.game_timer.timeout.connect(self.check_game_state)
        self.game_timer.start(100)  # Vérifie toutes les 100 ms

    def check_game_state(self):
        if self.echec_et_mat(self.current_player):
            self.game_timer.stop()
            winner = "Blancs" if self.current_player.couleur == 'n' else "Noirs"
            self.show_end_game_dialog("Échec et mat", winner)
        elif self.match_nul(self.current_player):
            self.game_timer.stop()
            self.show_end_game_dialog("Match nul", None)
        else:
            if self.current_player == self.joueur_noir:  # Tour de l'IA
                QTimer.singleShot(500, self.ia_move)

    def reset_highlight(self):
        # Réinitialise la couleur de toutes les cases
        for row in range(8):
            for col in range(8):
                button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + col)}{8-row}")
                if button:
                    color = "white" if (row + col) % 2 == 0 else "black"
                    button.setStyleSheet(f"background-color: {color}; font-size: 24px;")

    def isvalid_move(self, from_row, from_col, to_row, to_col):
        piece = self.board[from_row][from_col]
        if piece is None:
            return False

        # Gestion de la prise en passant
        m, n = None, None
        if isinstance(piece, Pion) and self.pion_avance_de_2_cases[-1] and self.moved_pieces:
            i, j = piece.position(self.board)
            last_piece = self.moved_pieces[-1]
            last_pos = last_piece.position(self.board)
            if last_pos == (i, j - 1):  # Pion à gauche
                m, n = (i - 1, j - 1) if piece.couleur == 'b' else (i + 1, j - 1)
            elif last_pos == (i, j + 1):  # Pion à droite
                m, n = (i - 1, j + 1) if piece.couleur == 'b' else (i + 1, j + 1)

        # Liste des cases accessibles (incluant la prise en passant)
        L = piece.cases_accessibles(self.board)
        if (m, n) is not None:
            L.append((m, n))

        # Vérifie si le mouvement est dans les cases accessibles
        if (to_row, to_col) not in L:
            return False

        # Vérifie si le joueur n'est pas en échec après le mouvement
        aux_to = self.board[to_row][to_col]
        aux_from = self.board[from_row][from_col]
        self.board[to_row][to_col] = piece
        self.board[from_row][from_col] = None

        is_valid = not self.echec(self.current_player)

        # Restaure l'échiquier
        self.board[from_row][from_col] = aux_from
        self.board[to_row][to_col] = aux_to

        return is_valid

    def move_piece(self, from_row, from_col, to_row, to_col):
        if not self.isvalid_move(from_row, from_col, to_row, to_col):
            return

        piece = self.board[from_row][from_col]
        promotion = None
        prise_en_passant = None
        petit_roque_possible,grand_roque_possible=self.roque_possible(self.current_player)

        # Roque
        if petit_roque_possible:
            R = Rn if self.current_player.couleur == 'n' else Rb
            i, j = R.position(self.board)
            if piece == R and (to_row, to_col) == (i, j + 2):
                self.roque(self.current_player,'petit')
                return
        if grand_roque_possible(self.current_player):
            R = Rn if self.current_player.couleur == 'n' else Rb
            i, j = R.position(self.board)
            if piece == R and (to_row, to_col) == (i, j - 2):
                self.roque(self.current_player,'grand')
                return

        # Déplacement normal
        self.board[from_row][from_col] = None
        self.pieces_prises.append(self.board[to_row][to_col])
        self.board[to_row][to_col] = piece

        # Mise à jour des attributs
        self.moved_pieces.append(piece)
        self.pion_avance_de_2cases(piece, from_row, to_row)
        prise_en_passant = self.prise_en_passant(piece, to_row, to_col)
        if prise_en_passant:
            self.pieces_prises[-1] = prise_en_passant

        if piece in self.a_bouge:
            self.a_bouge[piece] = True

        # Promotion
        promotion= self.promotion(piece)
        self.board[to_row][to_col] = promotion[-1]

        # Mise à jour de l'UI
        from_button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + from_col)}{8 - from_row}")
        to_button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + to_col)}{8 - to_row}")
        if from_button:
            from_button.setText("")
        if to_button:
            to_button.setText(piece)

        # Notation du coup
        move_notation = self.notation_move(piece, to_row, to_col, promotion, prise_en_passant)
        internal_notation = (f"{chr(97 + from_col)}{8 - from_row}-{move_notation}", promotion)
        self.move_history.append(internal_notation)
        self.listWidget.addItem(move_notation)

        # Changement de joueur
        self.current_player = self.joueur_noir if self.current_player == self.joueur_blanc else self.joueur_blanc
        self.selected_piece = None
        self.reset_highlight()
        if to_button:
            to_button.setStyleSheet("background-color: yellow; font-size: 24px;")

        # Échec
        if self.echec(self.current_player):
            R = Rn if self.current_player.couleur == 'n' else Rb
            row, col = R.position(self.board)
            button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + col)}{8 - row}")
            if button:
                button.setStyleSheet("background-color: red; font-size: 24px;")

        # Tour de l'IA
        if self.current_player == self.joueur_noir:
            QTimer.singleShot(500, self.ia_move)                                          #on rappelle la fonction start_game

    def roque(self, J, type_roque):
        """
        Effectue un roque (petit ou grand) pour le joueur J si possible.

        Paramètres
        ----------
        J : Joueur
            Le joueur qui tente de roquer.
        type_roque : str
            'petit' ou 'grand' pour spécifier le type de roque.

        Retourne
        -------
        bool
            True si le roque a été effectué, False sinon.
        """
        if type_roque == 'petit':
            roi = Rn if J.couleur == 'n' else Rb
            tour = Tn2 if J.couleur == 'n' else Tb2
            direction = 1  # Déplacement vers la droite
            cases_a_verifier = [(0, 1), (0, 2)]  # Cases entre roi et tour
        else:  # grand
            roi = Rn if J.couleur == 'n' else Rb
            tour = Tn1 if J.couleur == 'n' else Tb1
            direction = -1  # Déplacement vers la gauche
            cases_a_verifier = [(0, -1), (0, -2), (0, -3)]  # Cases entre roi et tour

        # Vérifie que le roi et la tour n'ont pas bougé
        if roi.a_bouge or tour.a_bouge:
            return False

        # Vérifie que le roi n'est pas en échec
        if self.echec(J):
            return False

        # Vérifie que les cases entre le roi et la tour sont vides
        i, j = roi.position(self.board)
        for di, dj in cases_a_verifier:
            if not (0 <= i + di < 8 and 0 <= j + dj < 8) or self.board[i + di][j + dj] is not None:
                return False

        # Simule le roque pour vérifier que le roi ne passe pas par une case en échec
        old_board = copy.deepcopy(self.board)
        old_roi_pos = (i, j)
        old_tour_pos = tour.position(self.board)

        # Déplace le roi
        self.board[i][j] = None
        self.board[i][j + 2 * direction] = roi

        # Vérifie que le roi n'est pas en échec après le déplacement
        if self.echec(J, board=self.board):
            self.board = old_board
            return False

        # Déplace la tour
        self.board[old_tour_pos[0]][old_tour_pos[1]] = None
        self.board[i][j + direction] = tour

        # Met à jour a_bouge pour le roi et la tour
        roi.a_bouge = True
        tour.a_bouge = True

        # Mise à jour de l'UI
        self.reset_highlight()
        self.update_ui_after_move(roi, old_roi_pos, (i, j + 2 * direction))
        self.update_ui_after_move(tour, old_tour_pos, (i, j + direction))

        # Changement de joueur
        self.current_player = self.joueur_noir if self.current_player == self.joueur_blanc else self.joueur_blanc

        return True

    def pion_avance_de_2cases(self, piece, from_row, to_row):
        if isinstance(piece, Pion):
            m = from_row + 2 if piece.couleur == 'n' else from_row - 2
            if to_row == m:
                self.pion_avance_de_2_cases.append(True)
            else:
                self.pion_avance_de_2_cases.append(False)
        self.pion_avance_de_2_cases.append(False)

    def prise_en_passant(self, piece, end_row, end_col):
        if isinstance(piece, Pion) and len(self.pion_avance_de_2_cases) >= 2 and self.pion_avance_de_2_cases[-2]:
            last_pion = self.moved_pieces[-2]
            k, l = last_pion.position(self.board)
            m, n = (k - 1, l) if piece.couleur == 'b' else (k + 1, l)
            if piece.position(self.board) == (m, n):
                self.board[k][l] = None
                button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + l)}{8 - k}")
                if button:
                    button.setText("")
                return last_pion
        return None

    def undo_last_move(self):
        if not self.move_history:
            return

        last_move, roque, promotion = self.move_history.pop()
        start_pos, notation_move = last_move.split('-')

        # Convertit les positions
        start_col, start_row = ord(start_pos[0]) - ord('a'), 8 - int(start_pos[1])
        end_col, end_row = ord(notation_move[0]) - ord('a'), 8 - int(notation_move[1])

        # Récupère les pièces
        piece = self.board[end_row][end_col]
        caught_piece = self.pieces_prises.pop() if self.pieces_prises else None

        # Annule le déplacement
        self.board[end_row][end_col] = caught_piece
        self.board[start_row][start_col] = piece

        # Met à jour les listes
        last_piece = self.moved_pieces.pop() if self.moved_pieces else None
        last_pion_avance = self.pion_avance_de_2_cases.pop() if self.pion_avance_de_2_cases else None

        # Gestion du roque
        if roque == 'petit':
            # Annule le petit roque
            from_row, from_col = (0, 6) if self.current_player.couleur == 'n' else (7, 6)
            to_row, to_col = (0, 4) if self.current_player.couleur == 'n' else (7, 4)
            from_row_tour, from_col_tour = (0, 5) if self.current_player.couleur == 'n' else (7, 5)
            to_row_tour, to_col_tour = (0, 7) if self.current_player.couleur == 'n' else (7, 7)

            roi = self.board[from_row][from_col]
            tour = self.board[from_row_tour][from_col_tour]

            self.board[from_row][from_col] = None
            self.board[to_row][to_col] = roi
            self.board[from_row_tour][from_col_tour] = None
            self.board[to_row_tour][to_col_tour] = tour

            # Retire les deux pièces de moved_pieces
            self.moved_pieces.pop()
            self.pion_avance_de_2_cases.pop()

        elif roque == 'grand':
            # Annule le grand roque
            from_row, from_col = (0, 2) if self.current_player.couleur == 'n' else (7, 2)
            to_row, to_col = (0, 4) if self.current_player.couleur == 'n' else (7, 4)
            from_row_tour, from_col_tour = (0, 3) if self.current_player.couleur == 'n' else (7, 3)
            to_row_tour, to_col_tour = (0, 0) if self.current_player.couleur == 'n' else (7, 0)

            roi = self.board[from_row][from_col]
            tour = self.board[from_row_tour][from_col_tour]

            self.board[from_row][from_col] = None
            self.board[to_row][to_col] = roi
            self.board[from_row_tour][from_col_tour] = None
            self.board[to_row_tour][to_col_tour] = tour

            # Retire les deux pièces de moved_pieces
            self.moved_pieces.pop()
            self.pion_avance_de_2_cases.pop()

        # Gestion de la promotion
        if promotion:
            self.board[end_row][end_col] = last_piece  # Remplace la Dame par le Pion

        # Met à jour l'UI
        from_button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + start_col)}{8 - start_row}")
        to_button = self.findChild(QtWidgets.QPushButton, f"{chr(97 + end_col)}{8 - end_row}")

        if from_button:
            from_button.setText(piece)
        if to_button:
            to_button.setText(caught_piece if caught_piece is not None else "")

        # Réinitialise la sélection
        self.selected_piece = None
        self.reset_highlight()

    def notation_move(self,piece, to_row, to_col,promotion=None,prise_en_passant=None):
        nota=['','','']            # [préfixe, prise, suffixe]
        adversaire = self.joueur_noir if self.current_player==self.joueur_blanc else self.joueur_blanc
        if self.echec(adversaire):
            nota[2]='+'
        if self.pieces_prises and self.pieces_prises[-1]:
            nota[1]='x'
        if self.echec_et_mat(adversaire):
            nota[2]='#'
        if promotion:
            nota[2] = '='+f'{promotion[1]}'
        if prise_en_passant:
            nota[1] = 'x e.p.'
        if not isinstance(piece, Pion):
            return f'{nota[0]}{piece}{nota[1]}{chr(97 + to_col)}{8 - to_row}{nota[2]}'   #notation pour les pions
        else:
            return f'{nota[0]}{nota[1]}{chr(97 + to_col)}{8 - to_row}{nota[2]}'          #notation pour les autres pièces

    def roque_possible(self, J):
        """
        Vérifie si un roque (petit ou grand) est possible pour le joueur J.

        Paramètres
        ----------
        J : Joueur
            Le joueur pour lequel vérifier le roque.

        Retourne
        -------
        str or bool
            'petit' si le petit roque est possible,
            'grand' si le grand roque est possible,
            False si aucun roque n'est possible.
        """
        result=[False,False]
        # Vérifie le petit roque
        if J.couleur == 'n':
            roi_petit = Rn
            tour_petit = Tn2
            roi_grand = Rn
            tour_grand = Tn1
        else:
            roi_petit = Rb
            tour_petit = Tb2
            roi_grand = Rb
            tour_grand = Tb1

        # Vérifie le petit roque
        if (not roi_petit.a_bouge and not tour_petit.a_bouge and
                not self.echec(J) and
                self.board[roi_petit.position(self.board)[0]][roi_petit.position(self.board)[1] + 1] is None and
                self.board[roi_petit.position(self.board)[0]][roi_petit.position(self.board)[1] + 2] is None):

            # Simule le roque pour vérifier que le roi ne passe pas par une case en échec
            old_board = copy.deepcopy(self.board)
            i, j = roi_petit.position(self.board)
            self.board[i][j] = None
            self.board[i][j + 2] = roi_petit
            if not self.echec(J,self.board):
                self.board = old_board
                result[0]='petit'
            self.board = old_board

        # Vérifie le grand roque
        if (not roi_grand.a_bouge and not tour_grand.a_bouge and
                not self.echec(J) and
                self.board[roi_grand.position(self.board)[0]][roi_grand.position(self.board)[1] - 1] is None and
                self.board[roi_grand.position(self.board)[0]][roi_grand.position(self.board)[1] - 2] is None and
                self.board[roi_grand.position(self.board)[0]][roi_grand.position(self.board)[1] - 3] is None):

            # Simule le roque pour vérifier que le roi ne passe pas par une case en échec
            old_board = copy.deepcopy(self.board)
            i, j = roi_grand.position(self.board)
            self.board[i][j] = None
            self.board[i][j - 2] = roi_grand
            if not self.echec(J, board=self.board):
                self.board = old_board
                result[1]='grand'
            self.board = old_board

        return resultgit

    def promotion(self, piece):
        row = piece.position(self.board)[0]
        if piece.couleur == 'b' and row == 0:
            # Boîte de dialogue pour choisir la pièce
            items = ["Dame", "Tour", "Cavalier", "Fou"]
            item, ok = QInputDialog.getItem(self, "Promotion", "Choisissez une pièce:", items, 0, False)
            if ok:
                if item == "Dame":
                    return True, Dame('b')
                elif item == "Tour":
                    return True, Tour('b')
                elif item == "Cavalier":
                    return True, Cavalier('b')
                elif item == "Fou":
                    return True, Fou('b')
        elif piece.couleur == 'n' and row == 7:
            items = ["Dame", "Tour", "Cavalier", "Fou"]
            item, ok = QInputDialog.getItem(self, "Promotion", "Choisissez une pièce:", items, 0, False)
            if ok:
                if item == "Dame":
                    return True, Dame('n')
                elif item == "Tour":
                    return True, Tour('n')
                elif item == "Cavalier":
                    return True, Cavalier('n')
                elif item == "Fou":
                    return True, Fou('n')
        return False, piece

    def echec_et_mat(self, J):
        roi = Rn if J.couleur == 'n' else Rb
        if not self.echec(J):
            return False  # Pas en échec → pas échec et mat
        # Vérifie que le roi n'a aucun coup légal
        return len(roi.cases_accesibles(self.board)) == 0

    def match_nul(self,J):
        return not self.echec(J) and all([piece.cases_accesibles(self.board) == [] for piece in J.pieces_vivantes(self.board)])

    def ia_move(self):
        def ia_move(self):
            if self.game_over:
                return  # Ne fait rien si la partie est terminée
            ...
        try:
            resultat = alpha_beta(self.board, self.ia, self.profondeur_courante, self.profondeur_max, self.heuristique, alpha=-np.inf, beta=np.inf)
        except Exception as e:
            print(f"Erreur dans alpha_beta: {e}")
            QMessageBox.information(self, "Erreur", "L'IA a rencontré une erreur.")
            self.game_over = True
            return
        if resultat[1]!=-np.inf:
            coup=resultat[0]
            piece,pos_finale=coup
            from_row,from_col=piece.position(self.board)
            to_row,to_col=pos_finale
            if self.isvalid_move(from_row, from_col, to_row, to_col):
                self.move_piece(from_row,from_col,to_row,to_col)
        else:
            QMessageBox.information(self, "Fin de partie", "Abandon de l'IA. Victoire de l'utilisateur!")
            self.game_over = True  # Désactive les mouvements suivants



#### logique du jeu de l'IA
    def heuristique(self, J):
        """
        Renvoie l'heuristique d'une configuration pour un joueur J.
        Basée sur :
        - Valeur des pièces (matériel)
        - Contrôle du centre
        - Mobilité des pièces
        - Pénalités pour les pions mal placés
        """
        h = 0
        c = J.couleur
        E = self.board

        # Valeurs des pièces (en centipions)
        valeurs = {
            Pion: 100,
            Cavalier: 300,
            Fou: 300,
            Tour: 500,
            Dame: 900,
            Roi: 0  # Le roi n'a pas de valeur matérielle
        }

        # Bonus pour les paires de fous
        nb_fou = 0

        for i, row in enumerate(E):
            for j, piece in enumerate(row):
                if piece is None:
                    continue

                # Valeur matérielle
                valeur = valeurs.get(type(piece), 0)
                if piece.couleur == c:
                    h += valeur
                else:
                    h -= valeur

                # Bonus pour les pièces du joueur J
                if piece.couleur == c:
                    # Bonus pour le contrôle du centre (cases d4, d5, e4, e5)
                    if (i, j) in [(3, 3), (3, 4), (4, 3), (4, 4)]:
                        h += 10  # Bonus modéré pour le centre

                    # Bonus pour la mobilité (nombre de coups légaux)
                    h += len(piece.cases_accessibles(E)) * 10  # 10 centipions par coup légal

                    # Spécifique aux pions
                    if isinstance(piece, Pion):
                        # Pénalité pour les pions sur les bords
                        if j in [0, 7]:
                            h -= 20

                        # Bonus pour les pions avancés (proches de la promotion)
                        if c == 'b' and i == 1:  # Pion blanc en 7ème ligne (index 1)
                            h += 50
                        elif c == 'n' and i == 6:  # Pion noir en 2ème ligne (index 6)
                            h += 50

                        # Bonus pour les pions connectés (protégés par un autre pion)
                        for di, dj in [(-1, -1), (-1, 1)]:
                            ni, nj = i + di, j + dj
                            if 0 <= ni < 8 and 0 <= nj < 8:
                                if isinstance(E[ni][nj], Pion) and E[ni][nj].couleur == c:
                                    h += 20

                    # Spécifique aux fous
                    if isinstance(piece, Fou):
                        nb_fou += 1

                    # Bonus pour le roque (roi en sécurité)
                    if isinstance(piece, Roi):
                        if (c == 'n' and (i, j) in [(0, 2), (0, 6)]) or (c == 'b' and (i, j) in [(7, 2), (7, 6)]):
                            h += 50

        # Bonus pour les paires de fous (contrôle de cases de couleurs opposées)
        if nb_fou >= 2:
            h += 50

        return h

    def coups_possibles(self,J):
        E=self.board
        L = []
        for piece in J.pieces_vivantes(E):   #pour chaque pièce vivante du joueur J
            for pos in piece.cases_accesibles(E):    #pour chaque position accessible par cette pièce
                L.append((piece, pos))          #on rajoute le coup (piece,position finale de la pièce)
        if self.petit_roque_possible(J):
            roi = Rn if J.couleur == 'n' else Rb
            L.append((roi, (roi.row, roi.col + 2)))  # Petit roque
        if self.grand_roque_possible(J):
            roi = Rn if J.couleur == 'n' else Rb
            L.append((roi, (roi.row, roi.col - 2)))  # Grand roque
        return L

    def resultat_coup(self, piece, pos_finale,roque=None,promotion=None,prise_en_passant=None):
        E = copy.deepcopy(self.board)  #crée une copie profonde de l'échiquier sur E, dont ne le modifie pas réelement, mais modifie sa copie
        k, l = piece.position(E)   #position actuelle de la pièce
        i, j = pos_finale          #sa position finale
        E[i][j] = piece            #modifie l'échiquier en faisant le coup
        E[k][l] = None
        # Gestion du roque
        if roque == 'petit':
            # Déplace le roi
            E[i][j] = piece
            E[k][l] = None
            # Déplace la tour
            tour = E[k][l + 3]  # Tour à droite du roi (ex: (0,7) pour les noirs)
            E[k][l + 1] = tour
            E[k][l + 3] = None
        elif roque == 'grand':
            # Déplace le roi
            E[i][j] = piece
            E[k][l] = None
            # Déplace la tour
            tour = E[k][l - 4]  # Tour à gauche du roi (ex: (0,0) pour les noirs)
            E[k][l - 1] = tour
            E[k][l - 4] = None
        # Gestion de la prise en passant
        elif prise_en_passant:
            # Supprime le pion capturé (à gauche ou à droite)
            if piece.couleur == 'b':
                E[i + 1][j] = None  # Pion noir capturé
            else:
                E[i - 1][j] = None  # Pion blanc capturé
        # Gestion de la promotion
        elif promotion:
            E[i][j] = promotion  # Remplace le pion par la pièce promue
        else:
            # Déplacement normal
            E[i][j] = piece
            E[k][l] = None
        return E                   #retourne le résultat du coup

    def alpha_beta(self, J, profondeur_courante=1, alpha=-np.inf, beta=np.inf, board=None, est_maximisant=True):
        if board is None:
            board = self.board
        if profondeur_courante >= profondeur_max:
            return None, self.heuristique(board, J)

        if est_maximisant:  # Tour de l'IA (maximiser)
            recompense_retenue, coup_retenu = -np.inf, None
            for piece, pos_finale in self.coups_possibles(J, board):
                nouvelle_config = self.resultat_coup(board, piece, pos_finale)
                next_J = self.joueur_noir if J == self.joueur_blanc else self.joueur_blanc
                coup, recompense = self.alpha_beta(next_J, profondeur_courante + 1, alpha, beta, nouvelle_config, False)
                if recompense > recompense_retenue:
                    recompense_retenue = recompense
                    coup_retenu = (piece, pos_finale)
                if recompense_retenue >= beta:
                    break
                if recompense > alpha:
                    alpha = recompense
            return coup_retenu, recompense_retenue
        else:  # Tour de l'adversaire (minimiser)
            recompense_retenue, coup_retenu = np.inf, None
            for piece, pos_finale in self.coups_possibles(J, board):
                nouvelle_config = self.resultat_coup(board, piece, pos_finale)
                next_J = self.joueur_noir if J == self.joueur_blanc else self.joueur_blanc
                coup, recompense = self.alpha_beta(next_J, profondeur_courante + 1, alpha, beta, nouvelle_config, True)
                if recompense < recompense_retenue:
                    recompense_retenue = recompense
                    coup_retenu = (piece, pos_finale)
                if recompense_retenue <= alpha:
                    break
                if recompense < beta:
                    beta = recompense
            return coup_retenu, recompense_retenue

    def echec(self,J):
        R=Rn if J.couleur=='n' else Rb
        return R.est_menacee(self.board)   #le roi est en échec s'il est directement menacé

    def show_end_game_dialog(self, result, winner):
        msg = QMessageBox(self)
        msg.setWindowTitle("Fin de partie")
        msg.setText(f"{result}\nGagnant : {winner}")
        msg.setStandardButtons(QMessageBox.Ok)

        # Sauvegarde dans la base de données
        try:
            moves_str = ", ".join([move[0] for move in self.move_history])
            self.cursor.execute('''
                INSERT INTO parties (date, result, winner, moves)
                VALUES (?, ?, ?, ?)
            ''', (datetime.now().strftime("%Y-%m-%d %H:%M:%S"), result, winner, moves_str))
            self.conn.commit()
        except Exception as e:
            print(f"Erreur lors de la sauvegarde de la partie: {e}")
            QMessageBox.warning(self, "Erreur", "La partie n'a pas pu être sauvegardée.")

        # Ajoute le bouton "Nouvelle partie"
        new_game_button = msg.addButton("Nouvelle partie", QMessageBox.ActionRole)
        msg.addButton(QMessageBox.Ok)  # Bouton "OK" classique

        msg.exec_()  # Affiche la boîte de dialogue

        # Si l'utilisateur clique sur "Nouvelle partie"
        if msg.clickedButton() == new_game_button:
            self.reset_game()  # Méthode pour réinitialiser le jeu

    def on_abandon_clicked(self):
        winner = "Noirs" if self.current_player.couleur == 'b' else "Blancs"
        self.show_end_game_dialog("Abandon", winner)

    def closeEvent(self, event):
        self.conn.close()
        event.accept()

    def reset_game(self):
        self.board = []
        self.setup_board()
        self.move_history = []
        self.pieces_prises = []
        self.moved_pieces = []
        self.pion_avance_de_2_cases = []
        self.current_player = self.joueur_blanc
        self.selected_piece = None

        # Réinitialise l'UI
        self.listWidget.clear()  # Efface l'historique des coups
        self.reset_highlight()  # Réinitialise la surbrillance des cases

        self.show_start_message()




class WelcomeDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Bienvenue")
        self.setModal(True)  # Bloque l'interaction avec la fenêtre principale
        self.setWindowFlags(Qt.Window | Qt.WindowCloseButtonHint)  # Garde la barre de titre

        # Active la transparence si nécessaire
        self.setAttribute(Qt.WA_TranslucentBackground)

        # Layout principal
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 20, 20, 20)  # Marges internes

        # Message de bienvenue
        label = QLabel("Bienvenue dans le jeu d'échecs !")
        label.setAlignment(Qt.AlignCenter)
        label.setStyleSheet("font-size: 24px; font-weight: bold; color: black;")
        layout.addWidget(label)

        # Bouton "Commencer une partie"
        self.start_button = QPushButton("Commencer une partie")
        self.start_button.setStyleSheet("""
            font-size: 18px;
            padding: 12px;
            background-color: #4CAF50;
            color: white;
            border-radius: 5px;
        """)
        self.start_button.clicked.connect(self.accept)  # Ferme la fenêtre et lance le jeu
        layout.addWidget(self.start_button)

        # Bouton "Fermer" (optionnel)
        close_button = QPushButton("Fermer")
        close_button.setStyleSheet("""
            font-size: 16px;
            padding: 8px;
            background-color: #f44336;
            color: white;
            border-radius: 5px;
        """)
        close_button.clicked.connect(self.reject)  # Ferme la fenêtre sans lancer le jeu
        layout.addWidget(close_button)

        # Style du fond
        self.setStyleSheet("""
            background-color: rgba(255, 255, 255, 230);
            border-radius: 15px;
            border: 2px solid black;
        """)

        # Ajuste la taille en fonction de l'écran
        screen = QDesktopWidget().screenGeometry()
        self.setFixedSize(screen.width() // 4, screen.height() // 5)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jeu = ChessGame()
    jeu.show()
    # Lance start_game après que la fenêtre soit affichée
    QtCore.QTimer.singleShot(100, jeu.start_game)  # Délai de 100 ms
    sys.exit(app.exec_())








