import unittest
from classe_Piece_et_filles_et_joueur import *
from chess import *




# tests/test_regles_jeu.py
class TestPion(unittest.TestCase):
    def setUp(self):
        self.E = [[None for _ in range(8)] for _ in range(8)]
    def test_deplacement_simple(self): ...
    def test_capture_diagonale(self): ...
    def test_deplacement_2_cases(self): ...

class TestRoi(unittest.TestCase):
    def test_echec(self): ...
    def test_roque_petit(self): ...
    def test_roque_grand(self): ...

# tests/test_ia.py
class TestAlphaBeta(unittest.TestCase):
    def test_coup_legal(self): ...
    def test_echec_et_mat(self): ...

class TestHeuristique(unittest.TestCase):
    def test_valeur_pieces(self): ...
    def test_controle_centre(self): ...

# tests/test_etat_jeu.py
class TestMovePiece(unittest.TestCase):
    def test_deplacement_pion(self): ...
    def test_capture(self): ...

class TestResetGame(unittest.TestCase):
    def test_reinitialisation(self): ...